default_install_hook_types:
  - pre-commit
  - post-checkout
  - post-merge
  - post-rewrite
repos:
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.8.13
    hooks:
      - id: uv-export
        name: main dependencies
        args: [--no-dev, --no-hashes, --output-file, requirements.txt]

      - id: uv-lock
repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.12.11
  hooks:
    # Run the linter.
    - id: ruff-check
      types_or: [ python, pyi ]
      args: [ --fix, --config=pyproject.toml ]
    # Run the formatter.
    - id: ruff-format
      types_or: [ python, pyi ]